# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-23 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20181223_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='image/default.jpg', upload_to='images/'),
        ),
    ]
